### ISSUE TITLE
Run Ad-Hoc Analytics On a Per-Sentence Basis Via API

### ISSUE THREAD

**Issue by imagineLife** [imagineLife/nlp-api#7]
# Implement Analysis-By-API
## A Problem: Applying New Analysis to Pre-Existing Data Is Cumbersome
I'm learning about NLP.  
I'm playing around with analysis "types": removing stopwords, testing sentiment score both _with_ & _without_ stopwords (I don't know the difference in sentiment scoring there...), NGrams...more to come there.  
ATOW, I cannot "easily" run a new analysis "type" on pre-existing data.  

## A Solution: Enable running analysis ad-hoc
I'm hoping to be able to make running new analysis "easier" via api:
- `GET speeches/:speechId/analysis/:analysisId/run` could "kick-off" a specific analysis of a specific speech

### "Stretch"
- be able to "crud" analysis types: create a "whole new analysis type" via api

## ToDo
- [ ] Build a `GET /analysis-types`, returning some ?json? info about analysis types
- [ ] Build a `GET speeches/:speechId/analysis/:analysisId/segmented/run` api that "kicks-off" an anlysis, by id, on a particular speech dataset, applying sentence-by-sentence (_segmented_)
- [ ] Build a `GET speeches/:speechId/analysis/:analysisId/run` api that "kicks-off" an anlysis, by id, on a particular speech dataset, applying to the entire speech text
